// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace AmaranthvilleWeb
{
    public partial class News
    {
        public const string Codename = "news";
        public const string TextCodename = "text";
        public const string NadpisCodename = "nadpis";
        public const string AutorCodename = "autor";
        public const string HlavniFotkaCodename = "hlavni_fotka";
        public const string GalerieCodename = "galerie";
        public const string UrlSlimakCodename = "url_slimak";

        public IRichTextContent Text { get; set; }
        public string Nadpis { get; set; }
        public string Autor { get; set; }
        public IEnumerable<Asset> HlavniFotka { get; set; }
        public IEnumerable<Asset> Galerie { get; set; }
        public string UrlSlimak { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}