// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace AmaranthvilleWeb
{
    public partial class PrezentacePsa
    {
        public const string Codename = "prezentace_psa";
        public const string UrlSlimacikCodename = "url_slimacik";
        public const string RodokmenCodename = "rodokmen";
        public const string PopisCodename = "popis";
        public const string FotkyCodename = "fotky";
        public const string JmenoCodename = "jmeno";

        public string UrlSlimacik { get; set; }
        public IEnumerable<Asset> Rodokmen { get; set; }
        public IRichTextContent Popis { get; set; }
        public IEnumerable<Asset> Fotky { get; set; }
        public string Jmeno { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}